### ISSUE TITLE
left, right movements is not smooth

### ISSUE THREAD

**Issue by iSpartak** [simpliflow/SFGaugeView#4]
Hi, it is me again ;)

Have complain from test users - subj

Try to use big range i.e. 1-100 or even bigger 1-9000

The first move or last move before begin or end of the range is fast and you not able to select let's say 5 or 95. In the middle it is ok.  

video from my tester: http://www.youtube.com/watch?v=cPUuTMInUbs&feature=youtu.be
it is not in english but check from 2.30 min

Actually might be related to available resources on iphone... may be not an issue

**Comment by tomgong** [comment]
Hi,

I tried to improve the precision. Now it should be much better. Nevertheless the control was not supposed to handle such big ranges (makes no sense for me to pick an exact number out of a range of 1-9000 with this control).

**Comment by iSpartak** [comment]
Thanks. And probably you are right about 'no sense' but 'customer is always right'
