### ISSUE TITLE
Can't run the example project

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [simpliflow/SFGaugeView#6]
Hi,

I downloaded the example project, navigated to the TestSFGaugeView folder and ran pod install  but I get the following error.

cd Downloads/SFGaugeView-master/TestSFGaugeView/

[!] Unable to satisfy the following requirements:
- `SFGaugeView (from`../`)` required by `Podfile`

**Comment by tomgong** [comment]
Hi,

please try to run

```
pod update
```

I think this issue is related to https://github.com/CocoaPods/CocoaPods/issues/1605.
I forgot to update the development Podfile to the newest version 0.0.6

**Comment by Isuru-Nanayakkara** [comment]
Thanks for the quick response. Now it's working fine. :+1:
